### ISSUE TITLE
Which is the proper composer.json file?

### ISSUE THREAD

**Issue by dancesWithCycles** [rdamashek/Community-Through-Caring#2]
Hi folks,
Thank you so much for providing and maintaining this repo.

[Here](https://github.com/rdamashek/Community-Through-Caring/blob/1ee835e6f569651a941aee6d74784053f644410a/README.md?plain=1#L35) you suggest to call ```composer update``` in the root directory.

This is the response on my GNU/Debian Bookworm host.

```
$ composer update
Composer could not find a composer.json file in /home/begerad/git/github/Community-Through-Caring
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
```

It sounds like the ```composer.json``` file is missing in the root directory.

I found 2 files with this name at other places by calling this instruction.

```
$ find . -name '*composer.json*' -type f
./MAIN/PHPMailer/composer.json
./MAIN/composer.json
```

Do you mind to clarify which is the right file and put it at the right place?

Cheers!

**Comment by faai5200** [comment]
@dancesWithCycles  Can you make sure you are in the `/MAIN` directory? Currently, the system files are located inside the MAIN directory. We will update the directory structure soon so that the root directory will contain the composer.json file. 

Hope this helps or let me know if there's still any questions

**Comment by dancesWithCycles** [comment]
@faai5200 Thank you for the remainder.
